import type { Metadata } from "next";
import { Inter, Lexend_Deca } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });
const lexend_Deca = Lexend_Deca({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Front end mentor challenge",
  description: "Generated by shadow",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${lexend_Deca.className}`}>
        {children}
      </body>
    </html>
  );
}
